import type {Config} from "stylelint";
export default {
	extends: [],
	overrides: [
		{customSyntax: `postcss-html`, files: [`**/*.html`, `**/*.svelte`]},
	],
	plugins: [`stylelint-order`],
	referenceFiles: [{files: [`source/client/styles/global.scss`]}],
	rules: {
		"alpha-value-notation": [`number`, {exceptProperties: []}],
		"annotation-no-unknown": [true, {ignoreAnnotations: []}],
		"at-rule-descriptor-no-unknown": [true],
		"at-rule-descriptor-value-no-unknown": [true],
		"at-rule-disallowed-list": [[]],
		"at-rule-empty-line-before": [`never`, {except: [], ignore: []}],
		"at-rule-no-deprecated": [true, {ignoreAtRules: []}],
		"at-rule-no-unknown": [true, {ignoreAtRules: []}],
		"at-rule-no-vendor-prefix": [true, {ignoreAtRules: []}],
		"at-rule-prelude-no-invalid": [true, {ignoreAtRules: []}],
		"at-rule-property-required-list": {},
		"block-no-empty": [true, {ignore: []}],
		"block-no-redundant-nested-style-rules": [true],
		"color-function-alias-notation": [`without-alpha`],
		"color-function-notation": [`modern`, {ignore: []}],
		"color-hex-alpha": [`always`],
		"color-hex-length": [`long`],
		"color-named": [`never`, {ignore: [], ignoreProperties: []}],
		"color-no-hex": [true],
		"color-no-invalid-hex": [true],
		"comment-empty-line-before": [`never`, {except: [], ignore: []}],
		"comment-no-empty": [true],
		"comment-whitespace-inside": [`always`],
		"container-name-pattern": [/[a-z]+(?:-[a-z]+)*/u],
		"custom-media-pattern": [/[a-z]+(?:-[a-z]+)*/u],
		"custom-property-empty-line-before": [`never`, {except: [], ignore: []}],
		"custom-property-no-missing-var-function": [true],
		"custom-property-pattern": [/[a-z]+(?:-[a-z]+)*/u],
		"declaration-block-no-duplicate-custom-properties": [
			true,
			{ignoreProperties: []},
		],
		"declaration-block-no-duplicate-properties": [
			true,
			{ignore: [], ignoreProperties: []},
		],
		"declaration-block-no-redundant-longhand-properties": [
			true,
			{ignoreLonghands: [], ignoreShorthands: []},
		],
		"declaration-block-no-shorthand-property-overrides": [true],
		"declaration-empty-line-before": [`never`, {except: [], ignore: []}],
		"declaration-no-important": [true],
		"declaration-property-unit-disallowed-list": [[], {ignore: []}],
		"declaration-property-value-disallowed-list": [[], {ignore: []}],
		"declaration-property-value-keyword-no-deprecated": [
			true,
			{ignoreKeywords: []},
		],
		"declaration-property-value-no-unknown": [true, {ignoreProperties: []}],
		"display-notation": [`full`],
		"font-family-name-quotes": [
			`always-unless-keyword`,
			{ignoreFontFamilyNames: []},
		],
		"font-family-no-duplicate-names": [true, {ignoreFontFamilyNames: []}],
		"font-family-no-missing-generic-family-keyword": [
			true,
			{ignoreFontFamilies: []},
		],
		"font-weight-notation": [`numeric`, {ignore: []}],
		"function-calc-no-unspaced-operator": [true],
		"function-disallowed-list": [[], {ignore: []}],
		"function-linear-gradient-no-nonstandard-direction": [true],
		"function-name-case": [`lower`, {ignoreFunctions: []}],
		"function-no-unknown": [true, {ignoreFunctions: []}],
		"function-url-no-scheme-relative": [true],
		"function-url-quotes": [`always`],
		"function-url-scheme-disallowed-list": [[], {ignore: []}],
		"hue-degree-notation": [`angle`],
		"import-notation": [`url`],
		"keyframe-block-no-duplicate-selectors": [true],
		"keyframe-declaration-no-important": [true],
		"keyframe-selector-notation": [`percentage`],
		"keyframes-name-pattern": [/[a-z]+(?:-[a-z]+)*/u],
		"layer-name-pattern": [/[a-z]+(?:-[a-z]+)*/u],
		"length-zero-no-unit": [
			true,
			{ignore: [], ignoreFunctions: [], ignorePreludeOfAtRules: []},
		],
		"lightness-notation": [`percentage`],
		"media-feature-name-disallowed-list": [[]],
		"media-feature-name-no-unknown": [true, {ignoreMediaFeatureNames: []}],
		"media-feature-name-no-vendor-prefix": [
			true,
			{ignoreMediaFeatureNames: []},
		],
		"media-feature-name-value-no-unknown": [true],
		"media-feature-range-notation": [`context`, {except: []}],
		"media-query-no-invalid": [true, {ignoreFunctions: []}],
		"media-type-no-deprecated": [true, {ignoreMediaTypes: []}],
		"named-grid-areas-no-invalid": [true],
		"nesting-selector-no-missing-scoping-root": [true, {ignoreAtRules: []}],
		"no-descending-specificity": [true, {ignore: []}],
		"no-duplicate-at-import-rules": [true],
		"no-duplicate-selectors": [
			true,
			{disallowInList: true, ignoreSelectors: []},
		],
		"no-invalid-double-slash-comments": [true],
		"no-invalid-position-at-import-rule": [true, {ignoreAtRules: []}],
		"no-invalid-position-declaration": [true, {ignoreAtRules: []}],
		"no-irregular-whitespace": [true],
		"no-unknown-animations": [true],
		"no-unknown-custom-media": [true],
		"no-unknown-custom-properties": [true],
		"order/custom-properties-alphabetical-order": [true],
		"order/order": [
			[
				`dollar-variables`,
				`custom-properties`,
				`at-rules`,
				`declarations`,
				`rules`,
			],
			{unspecified: `top`},
		],
		"order/properties-alphabetical-order": [true],
		"property-disallowed-list": [[]],
		"property-no-deprecated": [true, {ignoreProperties: []}],
		"property-no-unknown": [
			true,
			{
				checkPrefixed: true,
				ignoreAtRules: [],
				ignoreProperties: [],
				ignoreSelectors: [],
			},
		],
		"property-no-vendor-prefix": [true],
		"rule-empty-line-before": [`never`, {except: [], ignore: []}],
		"rule-selector-property-disallowed-list": [[], {ignore: []}],
		"selector-anb-no-unmatchable": [true],
		"selector-attribute-name-disallowed-list": [[]],
		"selector-attribute-operator-disallowed-list": [[]],
		"selector-attribute-quotes": [`always`],
		"selector-class-pattern": [/[a-z]+(?:-[a-z]+)*/u],
		"selector-combinator-disallowed-list": [[]],
		"selector-disallowed-list": [[], {ignore: [], splitList: true}],
		"selector-id-pattern": [/[a-z]+(?:-[a-z]+)*/u],
		"selector-nested-pattern": [/[a-z]+(?:-[a-z]+)*/u],
		"selector-no-qualifying-type": [true, {ignore: []}],
		"selector-no-vendor-prefix": [true, {ignoreSelectors: []}],
		"selector-not-notation": [`complex`],
		"selector-pseudo-class-disallowed-list": [[]],
		"selector-pseudo-class-no-unknown": [true, {ignorePseudoClasses: []}],
		"selector-pseudo-element-colon-notation": [`double`],
		"selector-pseudo-element-disallowed-list": [[]],
		"selector-pseudo-element-no-unknown": [true, {ignorePseudoElements: []}],
		"selector-type-case": [`lower`, {ignoreTypes: []}],
		"selector-type-no-unknown": [
			true,
			{ignore: [], ignoreNamespaces: [], ignoreTypes: []},
		],
		"shorthand-property-no-redundant-values": [true, {ignore: []}],
		"string-no-newline": [true, {ignore: []}],
		"syntax-string-no-invalid": [true],
		"unit-disallowed-list": [
			[],
			{ignoreFunctions: [], ignoreMediaFeatureNames: [], ignoreProperties: []},
		],
		"unit-no-unknown": [true, {ignoreFunctions: [], ignoreUnits: []}],
		"value-keyword-case": [
			`lower`,
			{
				camelCaseSvgKeywords: true,
				ignoreFunctions: [],
				ignoreKeywords: [],
				ignoreProperties: [],
			},
		],
		"value-no-vendor-prefix": [true, {ignoreValues: []}],
	},
} as const satisfies Config;
