env:
  DEBIAN__DOCKER_IMAGE__TAG__DATE: "20251208"
  NODE_JS__VERSION: "25.9.0"
jobs:
  build_docker_image:
    name: "Build a Docker image"
    needs: ["release"]
    outputs:
      release_version: "${{needs.release.outputs.release_version}}"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Download the release"
        uses: "robinraju/release-downloader@v1.12"
        with:
          tag: "${{needs.release.outputs.release_version}}"
          tarBall: true
      - name: "Unpack the release"
        run: |
          tar -xzf ./${{github.event.repository.name}}-${{needs.release.outputs.release_version}}.tar.gz
      - name: "Remove tarball"
        run: |
          rm ./${{github.event.repository.name}}-${{needs.release.outputs.release_version}}.tar.gz
      - name: "Move the files to the current directory"
        run: |
          shopt -s dotglob
          mv ./${{github.event.repository.owner.login}}-${{github.event.repository.name}}-*/* ./
          shopt -u dotglob
          rm -rf ./${{github.event.repository.owner.login}}-${{github.event.repository.name}}-*/
      - name: "Build a Docker image"
        run: |
          docker build --tag=${{vars.DOCKER_REGISTRY__REPOSITORY__NAME}}:${{needs.release.outputs.release_version}} --file=Dockerfile --build-arg="DEBIAN__DOCKER_IMAGE__TAG__DATE=${{env.DEBIAN__DOCKER_IMAGE__TAG__DATE}}" --build-arg="NODE_JS__VERSION=${{env.NODE_JS__VERSION}}" .
      - name: "Upload the Docker image as an artifact"
        uses: "ishworkh/container-image-artifact-upload@v2.0.0"
        with:
          image: "${{vars.DOCKER_REGISTRY__REPOSITORY__NAME}}:${{needs.release.outputs.release_version}}"
  publish_to_docker_registry:
    name: "Publish to the Docker registry"
    needs: ["build_docker_image"]
    runs-on: "ubuntu-latest"
    steps:
      - name: "Download the built Docker image"
        uses: "ishworkh/container-image-artifact-download@v2.1.0"
        with:
          image: "${{vars.DOCKER_REGISTRY__REPOSITORY__NAME}}:${{needs.build_docker_image.outputs.release_version}}"
      - name: "Login to the Docker registry"
        uses: "docker/login-action@v3"
        with:
          password: "${{secrets.DOCKER_REGISTRY__USER__PASSWORD}}"
          registry: "${{vars.DOCKER_REGISTRY__HOST_NAME}}"
          username: "${{vars.DOCKER_REGISTRY__USER__NAME}}"
      - name: 'Push the Docker image to the registry with a "${{needs.build_docker_image.outputs.release_version}}" tag'
        run: |
          docker push ${{vars.DOCKER_REGISTRY__HOST_NAME}}/${{vars.DOCKER_REGISTRY__REPOSITORY__NAME}}:${{needs.build_docker_image.outputs.release_version}}
      - name: 'Add a "latest" tag to the Docker image'
        run: |
          docker tag ${{vars.DOCKER_REGISTRY__HOST_NAME}}/${{vars.DOCKER_REGISTRY__REPOSITORY__NAME}}:${{needs.build_docker_image.outputs.release_version}} ${{vars.DOCKER_REGISTRY__HOST_NAME}}/${{vars.DOCKER_REGISTRY__REPOSITORY__NAME}}:latest
      - name: 'Push the Docker image to the registry with a "latest" tag'
        run: |
          docker push ${{vars.DOCKER_REGISTRY__HOST_NAME}}/${{vars.DOCKER_REGISTRY__REPOSITORY__NAME}}:latest
  release:
    name: "Release"
    outputs:
      release_version: "${{steps.remember_release_version.outputs.release_version}}"
    permissions:
      contents: "write"
      pull-requests: "write"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v7.0.1"
        with:
          fetch-depth: 0
      - name: "Setup Node.js"
        uses: "actions/setup-node@v6.3.0"
        with:
          cache: "npm"
          node-version: "${{env.NODE_JS__VERSION}}"
      - name: "Configure Git"
        run: |
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config user.name "${GITHUB_ACTOR}"
      - name: "Install the dependencies"
        run: |
          npm ci --registry=https://registry.npmjs.org --//registry.npmjs.org/:_authToken=${{secrets.NPM__REGISTRY__ACCESS_TOKEN}}
      - env:
          GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"
          NODE_OPTIONS: "--import=@native-typescript/loader-of-typescript-for-node-js"
        name: "Release"
        run: |
          npm run release-it -- --ci --verbose
      - id: "remember_release_version"
        name: "Remember the release version"
        run: |
          echo "release_version=$(npm pkg get version | tr -d '"')" >> $GITHUB_OUTPUT
name: "Releasing"
on:
  workflow_dispatch:
